### ISSUE TITLE
Error when using my own images

### ISSUE THREAD

**Issue by Phoenix-313** [luisquintanilla/DeppLearning_ImageClassification_API#1]
Hi, 

Many thanks for the great tutorial on detecting cracks in concrete. 

I'm trying to use a different set of images that I already have (water leak or no leak). The total number of images for the two classes (leak or no leak) is less than the total number of crack/no crack images that are used for the tutorial. I tried to replace the contents of the assets folder (UD/CD) with my own images (leak/no leak), however, I keep getting the following exception when calling the ClassifySingleImage method :    

System.InvalidOperationException: 'Sequence contains no elements'

It seems to me that the program is not able to find the image to be classified. I should mention that even if I use the provided images by the tutorial (UD and CD) I get the same error if I remove some of the images from the folders.  

Could you please help?

**Comment by luisquintanilla** [comment]
Hi @Phoenix-313 

Glad you found it useful. However this sample is not the one used in the tutorial. This sample uses an older preview version of the API. I would suggest taking a look at the sample in the dotnet/machinelearning-samples repo instead: https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Binary

This is the sample used in the Microsoft Docs tutorial. 

https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification-api-transfer-learning

Now, to your question. The number of images you use for training should not matter. Although the performance of your model will typically improve as you provide more data. 

I suspect a reason why you might be getting the error is because you provide a workspace path. The intent of that parameter is to compute the bottleneck values the first time. Then, if you want to **work with the same data** but maybe want to explore using different hyperparameters, it uses those bottleneck values rather than recomputing them. However, if you change the data or try to use a different dataset without clearing out those values you might run into issues because it tries to use the cached data and if that data is different or has changed (file path) then it might throw an error. I would suggest a) clearing out the workspace path if you're going to work with different datasets or b) don't set a workspace path so bottleneck values are not cached. 

Something else that might differ is how you run the application. This app was built using Visual Studio. However, on Linux / Mac, paths may not exactly map out exactly the same. I'd suggest as part of debugging to make sure that the path where you're pointing to is correct. 

If you continue to run into issues, please raise them on the [dotnet/machinelearning-samples repo](https://github.com/dotnet/machinelearning-samples/issues)

**Comment by Phoenix-313** [comment]
You are absolutely correct! Thank you very much!
